Repository Quick-Project/ddoboja, pull requests merged in 2022-12, with the labels that each got.

#17 🎨 style : 결과창 컴포넌트 텍스트 수정 및 맥주 페이지 다크모드 대응 css 수정
  components/Maekjoo/WriterContainer.js
  components/ResultPage/IDECompo.js
Labels: 🖼 HTML&CSS

#20 🐛 fix : modal.js 데이터 받아진 후에만 에러 출력
  components/Maekjoo/Modal.js
Labels: 🚨 BugFix

#21 📦 chore : VSC CSS 수정 및 로직 추가
  components/VSC/BottomLine.js
  components/VSC/Button.js
  components/VSC/LeftFolderLine.js
  components/VSC/MainInput.js
  components/VSC/NewLetterTab.js
  components/VSC/Tab.js
  components/VSC/newLetter.js
  pages/vscodestates.js
  pages/vscodestatesNew.js
Labels: ⛲ Feature

#25 🎨 style : progamers css 수정
  components/Main/Render.js
  components/Progamers/Footer.js
  components/Progamers/Header.js
  components/Progamers/Main.js
  pages/vscodestatesNew.js
Labels: 🖼 HTML&CSS, 🚨 BugFix

#26 🐛 fix : 로그인 유저 관련 DB 접근법 수정, 로그인 유저 예외처리, recoil 데이터 수정
  components/Search.js
  components/apis/checkUser.js
  components/hook/useGetname.js
  pages/index.js
  pages/maekjoo.js
Labels: 🚨 BugFix

#35 🐛 fix : progamers 예외 처리 완료
  pages/maekjoo.js
  pages/progamers.js
Labels: 🚨 BugFix

#48 📦 chore : 패딩 삭제 및 width 수정
  components/VSC/BottomLine.js
Labels: 🚨 BugFix

#52 🎨 style : overflow hidden 수정
  components/VSC/BottomLine.js
  pages/vscodestates.js
  styles/globals.css
Labels: 🚨 BugFix

#53 🎨 style : bottom line 길이 수정
  components/VSC/BottomLine.js
Labels: 🖼 HTML&CSS

#54 🎨 style : overflow, width 수정
  components/VSC/MainInput.js
  pages/vscodestates.js
Labels: 🖼 HTML&CSS

#55 🎨 style : overflow, width 수정
  pages/maekjoo.js
Labels: 🖼 HTML&CSS
